jobs:
- job: smoke_test
  displayName: Smoke Test (Debug Build of MyExtensionsApp.1)
  pool:
    vmImage: $(windowsAgent)
  steps:
    - checkout: self
      fetchDepth: 0

    - template: ../steps/install-dependencies.yml
      parameters:
        targetPlatform: 'wasm'

    - task: MSBuild@1
      inputs:
        solution: ./MyExtensionsApp.1/MyExtensionsApp.1.csproj
        msbuildArguments: '/r'
